# Generated by Django 3.2.9 on 2022-02-02 00:27

from django.db import migrations, models
import django.db.models.deletion
import host.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('vizier_id', models.CharField(max_length=20)),
                ('id_column', models.CharField(max_length=20)),
                ('ra_column', models.CharField(max_length=20)),
                ('dec_column', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalResourceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=20)),
                ('response_status', models.CharField(max_length=20)),
                ('request_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tns_name', models.CharField(max_length=20)),
                ('tns_id', models.IntegerField()),
                ('tns_prefix', models.CharField(max_length=20)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
                ('public_timestamp', models.DateTimeField(blank=True, null=True)),
                ('host_match_status', models.CharField(default='not processed', max_length=20)),
                ('image_download_status', models.CharField(default='not processed', max_length=20)),
                ('catalog_photometry_status', models.CharField(default='not processed', max_length=20)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.host')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sedpy_id', models.CharField(max_length=20)),
                ('hips_id', models.CharField(max_length=20)),
                ('vosa_id', models.CharField(max_length=20)),
                ('image_download_method', models.CharField(max_length=20)),
                ('pixel_size_arcsec', models.FloatField()),
                ('wavelength_eff_angstrom', models.FloatField()),
                ('wavelength_min_angstrom', models.FloatField()),
                ('wavelength_max_angstrom', models.FloatField()),
                ('vega_zero_point_jansky', models.FloatField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Cutout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.FileField(blank=True, null=True, upload_to=host.models.fits_file_path)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.filter')),
                ('transient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogPhotometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('mag_column', models.CharField(max_length=20)),
                ('mag_error_column', models.CharField(max_length=20)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.catalog')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.filter')),
            ],
        ),
        migrations.AddField(
            model_name='catalog',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.survey'),
        ),
    ]
