# Generated by Django 3.2.9 on 2022-01-06 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sedpy_id', models.CharField(max_length=20)),
                ('hips_id', models.CharField(max_length=20)),
                ('vosa_id', models.CharField(max_length=20)),
                ('image_download_method', models.CharField(max_length=20)),
                ('pixel_size_arcsec', models.FloatField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.survey')),
            ],
        ),
    ]
