# Generated by Django 3.2.9 on 2022-01-10 22:00

from django.db import migrations, models
import django.db.models.deletion
import host.models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.FileField(blank=True, null=True, upload_to=host.models.fits_file_path)),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.filter')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host')),
            ],
        ),
    ]
