# Generated by Django 3.2.9 on 2022-02-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
