# Generated by Django 3.2.9 on 2022-03-02 01:26
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("host", "0001_initial")]

    operations = [
        migrations.RemoveField(
            model_name="transient", name="catalog_photometry_status"
        ),
        migrations.RemoveField(model_name="transient", name="host_match_status"),
        migrations.RemoveField(model_name="transient", name="image_download_status"),
    ]
