# Generated by Django 3.2.9 on 2022-05-12 18:31
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aperture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
                ('orientation', models.FloatField()),
                ('semi_major_axis_arcsec', models.FloatField()),
                ('semi_minor_axis_arcsec', models.FloatField()),
                ('type', models.CharField(max_length=20)),
                ('cutout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.cutout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transient',
            name='catalog_photometry_status',
        ),
        migrations.RemoveField(
            model_name='transient',
            name='host_match_status',
        ),
        migrations.RemoveField(
            model_name='transient',
            name='image_download_status',
        ),
        migrations.AddField(
            model_name='taskregister',
            name='last_processing_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AperturePhotometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux', models.FloatField()),
                ('flux_error', models.FloatField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
                ('magnitude_error', models.FloatField(blank=True, null=True)),
                ('aperture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.aperture')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.filter')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.transient')),
            ],
        ),
        migrations.AddField(
            model_name='aperture',
            name='transient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient'),
        ),
    ]
