# Generated by Django 3.2.9 on 2022-01-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_host_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Cutout',
        ),
    ]
