# Generated by Django 3.2.9 on 2022-01-13 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_rename_image_cutout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ra_deg', models.FloatField()),
                ('dec_deg', models.FloatField()),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.host')),
            ],
        ),
    ]
