# Generated by Django 3.2.9 on 2022-02-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_auto_20220211_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='hips_id',
            field=models.CharField(max_length=250),
        ),
    ]
