# Generated by Django 3.2.9 on 2022-07-18 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_filter_kcorrect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectorresult',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.host'),
        ),
    ]
