# Generated by Django 3.2.9 on 2022-05-03 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aperture',
            name='filter',
        ),
        migrations.RemoveField(
            model_name='aperture',
            name='host',
        ),
        migrations.AddField(
            model_name='aperture',
            name='cutout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.cutout'),
        ),
        migrations.CreateModel(
            name='AperturePhotometry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flux', models.FloatField()),
                ('flux_error', models.FloatField()),
                ('magnitude', models.FloatField()),
                ('magnitude_error', models.FloatField()),
                ('aperture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.aperture')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.filter')),
                ('transient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.transient')),
            ],
        ),
    ]
