# Generated by Django 3.2.9 on 2022-01-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_transient'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='processing_status',
            field=models.CharField(default='not processed', max_length=20),
        ),
    ]
