# Generated by Django 3.2.9 on 2022-02-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_alter_filter_hips_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
