# Generated by Django 3.2.9 on 2022-05-05 19:52
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_auto_20220503_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='aperture',
            name='transient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient'),
        ),
    ]
