# Generated by Django 3.2.9 on 2022-01-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_transient_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transient',
            name='name',
        ),
        migrations.AddField(
            model_name='transient',
            name='tns_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='tns_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='tns_prefix',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
