# Generated by Django 3.2.9 on 2022-02-15 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_alter_catalog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogphotometry',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
