# Generated by Django 3.2.9 on 2022-05-06 22:31
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_aperture_transient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturephotometry',
            name='flux_error',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aperturephotometry',
            name='magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aperturephotometry',
            name='magnitude_error',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
