# Generated by Django 3.2.9 on 2022-08-22 15:41
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("host", "0006_host_milkyway_dust_reddening"),
    ]

    operations = [
        migrations.AddField(
            model_name="transient",
            name="processing_status",
            field=models.CharField(default="processing", max_length=20),
        ),
    ]
