# Generated by Django 3.2.9 on 2022-01-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_auto_20220121_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResourceCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=20)),
                ('time_called', models.DateTimeField()),
                ('response_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='transient',
            name='processing_status',
        ),
        migrations.AddField(
            model_name='transient',
            name='host_match_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transient',
            name='public_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='tns_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transient',
            name='tns_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transient',
            name='tns_prefix',
            field=models.CharField(max_length=20),
        ),
    ]
