# Generated by Django 3.2.9 on 2022-02-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0006_alter_catalogphotometry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transient',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
