# Generated by Django 3.2.9 on 2022-01-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20220125_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transient',
            name='host_match_status',
            field=models.CharField(default='not processed', max_length=20),
        ),
    ]
