# Generated by Django 3.2.9 on 2022-08-22 23:35
import django.db.models.deletion
import host.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0007_transient_processing_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEDFittingResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posterior",
                    models.FileField(
                        blank=True, null=True, upload_to=host.models.hdf5_file_path
                    ),
                ),
                ("log_mass_16", models.FloatField(blank=True, null=True)),
                ("log_mass_50", models.FloatField(blank=True, null=True)),
                ("log_mass_84", models.FloatField(blank=True, null=True)),
                ("log_sfr_16", models.FloatField(blank=True, null=True)),
                ("log_sfr_50", models.FloatField(blank=True, null=True)),
                ("log_sfr_84", models.FloatField(blank=True, null=True)),
                ("log_ssfr_16", models.FloatField(blank=True, null=True)),
                ("log_ssfr_50", models.FloatField(blank=True, null=True)),
                ("log_ssfr_84", models.FloatField(blank=True, null=True)),
                ("log_age_16", models.FloatField(blank=True, null=True)),
                ("log_age_50", models.FloatField(blank=True, null=True)),
                ("log_age_84", models.FloatField(blank=True, null=True)),
                ("log_tau_16", models.FloatField(blank=True, null=True)),
                ("log_tau_50", models.FloatField(blank=True, null=True)),
                ("log_tau_84", models.FloatField(blank=True, null=True)),
                (
                    "aperture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="host.aperture",
                    ),
                ),
                (
                    "transient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="host.transient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="host",
            name="photometric_redshift",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ProspectorResult",
        ),
    ]
