# Generated by Django 3.2.9 on 2022-01-25 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_alter_transient_host_match_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalresourcecall',
            name='time_called',
        ),
    ]
