# Generated by Django 3.2.9 on 2022-10-25 23:34
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0008_auto_20220822_2335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aperturephotometry",
            name="flux",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
