# Generated by Django 3.2.9 on 2022-11-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_alter_transient_tns_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturephotometry',
            name='flux',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
