# Generated by Django 3.2.9 on 2022-01-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_remove_externalresourcecall_time_called'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalresourcecall',
            name='call_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
