# Generated by Django 3.2.9 on 2022-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_externalresourcecall_call_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalresourcecall',
            old_name='call_time',
            new_name='request_time',
        ),
    ]
