# Generated by Django 3.2.9 on 2022-11-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_alter_aperturephotometry_flux'),
        ('host', '0010_auto_20221030_1810'),
    ]

    operations = [
    ]
