# Generated by Django 3.2.9 on 2023-03-27 23:48
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0010_auto_20221030_1810"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="magnitude_zero_point_keyword",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
