# Generated by Django 3.2.9 on 2023-04-11 22:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0011_filter_magnitude_zero_point_keyword"),
    ]

    operations = [
        migrations.AddField(
            model_name="filter",
            name="ab_offset",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
