# Generated by Django 3.2.9 on 2022-01-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_transient_image_download_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutout',
            name='host',
        ),
        migrations.AddField(
            model_name='cutout',
            name='transient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient'),
        ),
    ]
