# Generated by Django 3.2.9 on 2023-05-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_filter_ab_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedfittingresult',
            name='mass_surviving_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
