# Generated by Django 3.2.9 on 2024-02-05 02:40

from django.db import migrations, models
import host.models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_alter_aperturephotometry_is_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedfittingresult',
            name='chains_file',
            field=models.FileField(blank=True, null=True, upload_to=host.models.npz_chains_file_path),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to=host.models.npz_model_file_path),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='percentiles_file',
            field=models.FileField(blank=True, null=True, upload_to=host.models.npz_percentiles_file_path),
        ),
    ]
