# Generated by Django 3.2.9 on 2024-04-02 20:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("host", "0018_auto_20240205_0240"),
    ]

    operations = [
        migrations.AddField(
            model_name="cutout",
            name="message",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
