# Generated by Django 3.2.9 on 2024-04-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0019_cutout_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='transient',
            name='progress',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
