# Generated by Django 3.2.9 on 2024-04-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0020_transient_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transient',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
