# Generated by Django 5.0.4 on 2024-05-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0021_alter_transient_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_query', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
