# Generated by Django 5.0.4 on 2024-05-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0022_externalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transient',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
