# Generated by Django 5.0.7 on 2024-08-15 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0024_load_fixtures'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust1_fraction_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust1_fraction_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust1_fraction_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust2_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust2_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust2_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust_index_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust_index_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='dust_index_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_qpah_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_qpah_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_qpah_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_umin_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_umin_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='duste_umin_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='gas_logz_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='gas_logz_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='gas_logz_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_agn_tau_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_agn_tau_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_agn_tau_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_duste_gamma_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_duste_gamma_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_duste_gamma_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_fagn_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_fagn_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='log_fagn_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='logzsol_16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='logzsol_50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='logzsol_84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StarFormationHistoryResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logsfr_16', models.FloatField(blank=True, null=True)),
                ('logsfr_50', models.FloatField(blank=True, null=True)),
                ('logsfr_84', models.FloatField(blank=True, null=True)),
                ('logsfr_tmin', models.FloatField(blank=True, null=True)),
                ('logsfr_tmax', models.FloatField(blank=True, null=True)),
                ('aperture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.aperture')),
                ('transient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.transient')),
            ],
        ),
        migrations.AddField(
            model_name='sedfittingresult',
            name='logsfh',
            field=models.ManyToManyField(blank=True, to='host.starformationhistoryresult'),
        ),
    ]
