FROM python:3.11

RUN curl https://dl.min.io/client/mc/release/linux-amd64/mc \
    -o /usr/local/bin/mc && \
    chmod +x /usr/local/bin/mc

COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt --no-cache-dir
